quiz_data = {
    # Nhóm 1: Cấu trúc phân tử và liên kết
    "What kind of bond results from polar covalent bonds in water?": "Hydrogen bond",
    "In water, electrons spend more time near which atom?": "Oxygen",
    "Water is a ______ molecule because its charge is unevenly distributed.": "Polar",
    "What property allows water molecules to form bonds with each other?": "Polarity",
    "A hydrogen bond forms between the partial positive charge of hydrogen and the partial _____ charge of oxygen.": "Negative",
    "What is the partial charge of a hydrogen atom in a water molecule?": "Delta positive",
    "What is the partial charge of an oxygen atom in a water molecule?": "Delta negative",
    "How many physical states can water exist in naturally?": 3,
    "The molecule that supports all of life is ____.": "Water",
    "What type of bond holds a single water molecule's atoms together?": "Polar covalent bond",

    # Nhóm 2: Đặc tính Cohesion và Adhesion
    "What phenomenon holds water molecules together collectively?": "Cohesion",
    "What property helps transport water against gravity in plants?": "Cohesion",
    "What is the attraction between water and different substances called?": "Adhesion",
    "Water sticking to plant cell walls is an example of ____.": "Adhesion",
    "What property measures how difficult it is to break the surface of a liquid?": "Surface tension",
    "Water has an unusually high surface tension due to ____ bonding.": "Hydrogen",
    "What biological transport process is aided by cohesion and adhesion?": "Water transport in plants",
    "Where do hydrogen bonds form to create surface tension?": "Air-water interface",
    "Cohesion is due to hydrogen bonding between _____ molecules.": "Water",
    "Adhesion is an attraction between water and _____ molecules.": "Other",

    # Nhóm 3: Điều hòa nhiệt độ
    "Water absorbs heat from warmer air and releases it to _____ air.": "Cooler",
    "Water can absorb a large amount of heat with only a slight change in its own ____.": "Temperature",
    "The amount of heat absorbed or lost for 1g of substance to change 1 degree Celsius is called ____.": "Specific heat",
    "The specific heat of water is ____ calorie per gram per degree Celsius.": "One",
    "Why does water resist changing its temperature?": "High specific heat",
    "Heat is absorbed when hydrogen bonds _____.": "Break",
    "Heat is released when hydrogen bonds _____.": "Form",
    "The process where a liquid's surface cools as it evaporates is called ____.": "Evaporative cooling",
    "What process helps stabilize temperature in organisms and bodies of water?": "Evaporative cooling",
    "Transition of a substance from liquid to gas is called ____.": "Evaporation",
    "What is the heat a liquid must absorb for 1g to be converted to gas?": "Heat of vaporization",

    # Nhóm 4: Sự dãn nở khi đóng băng
    "Ice floats because hydrogen bonds in ice are more ____ than in liquid water.": "Ordered",
    "Ice is _____ dense than liquid water.": "Less",
    "At what temperature does water reach its greatest density?": 4,
    "If ice _____, all bodies of water would eventually freeze solid.": "Sank",
    "What state of water has hydrogen bonds constantly breaking and reforming?": "Liquid",
    "What state of water has hydrogen bonds that are stable and 'arm's length'?": "Ice",
    "Expansion upon _____ makes water unique compared to other liquids.": "Freezing",
    "What would happen to life on Earth if ice was denser than water?": "Life would be impossible",
    "The floating of ice is a result of ______ bonding.": "Hydrogen",

    # Nhóm 5: Dung môi và pH
    "Water is known as the _____ solvent of life.": "Universal",
    "A completely homogeneous mixture of substances is called a ____.": "Solution",
    "The dissolving agent of a solution is the ____.": "Solvent",
    "The substance that is dissolved in a solution is the ____.": "Solute",
    "An ______ solution is one in which water is the solvent.": "Aqueous",
    "A substance that has an affinity for water is called ____.": "Hydrophilic",
    "A substance that does not have an affinity for water is called ____.": "Hydrophobic",
    "Oil molecules are hydrophobic because they have _____ bonds.": "Nonpolar",
    "What scale describes whether a solution is acidic or basic?": "pH scale",
    "What is the main product of fossil fuel combustion that threatens oceans?": "CO2",
    "CO2 dissolved in seawater forms ____ acid.": "Carbonic",
    "The process of CO2 lowering the ocean's pH is called ____.": "Ocean acidification",

    "Why did the student eat his homework?": "Because the teacher said it was a piece of cake.",
    "Why did the book look tired?": "Because it had too many chapters.",
    "Why did the computer hate homework?": "Because it was too much processing.",
    "Why did the dog sit in the shade?": "Because it didn’t want to be a hot dog.",
    "Why did the light bulb fail school?": "Because it wasn’t very bright.",
    "Why did the fish blush?": "Because it saw the ocean’s bottom.",
    "Why did the keyboard break up with the mouse?": "There was no connection.",
    "Why did the clock get kicked out of class?": "Because it kept ticking.",
    "Why did the laptop go to bed early?": "Because it needed to recharge.",
    "Why did the broom get a promotion?": "Because it swept the competition.",

    # Nhóm Địa lý (1-30)
    "How many states are in the USA?": 50,
    "How many cities are in Vietnam?": 63,
    "How many continents are there on Earth?": 7,
    "How many oceans are there in the world?": 5,
    # ... (Bạn có thể thêm tiếp các câu tương tự)

    # Nhóm Cơ thể người & Khoa học (31-60)
    "How many bones are in the adult human body?": 206,
    "How many teeth does an adult human usually have?": 32,
    "How many planets are in our solar system?": 8,
    "How many days are in a leap year?": 366,
    "How many minutes are in an hour?": 60,

    # Nhóm Thời gian & Quy ước (61-100)
    "How many months are in a year?": 12,
    "How many weeks are in a year?": 52,
    "How many hours are in a day?": 24,
    "How many seconds are in a minute?": 60,
    "How many degrees are in a right angle?": 90,
    "How many millimeters are in a centimeter?": 10,
    "How many centimeters are in a meter?": 100,
    "How many meters are in a kilometer?": 1000,
     "Why did the chicken cross the road?": "To get to the other side.",
    "Why don't scientists trust atoms?": "Because they make up everything.",
    "Why was the math book sad?": "Because it had too many problems.",
    "Why did the scarecrow win an award?": "Because he was outstanding in his field.",
    "Why don’t skeletons fight each other?": "They don’t have the guts.",
    "Why did the computer catch a cold?": "Because it left its Windows open.",
    "Why was six afraid of seven?": "Because seven eight nine.",
    "Why did the bicycle fall over?": "Because it was two-tired.",
    "Why can’t your nose be 12 inches long?": "Because then it would be a foot.",
    "Why did the golfer bring two pairs of pants?": "In case he got a hole in one.",

    "Why don’t eggs tell jokes?": "They’d crack each other up.",
    "Why did the coffee file a police report?": "It got mugged.",
    "Why did the math teacher call the student average?": "Because he was mean.",
    "Why don’t programmers like nature?": "Too many bugs.",
    "Why did the cookie go to the doctor?": "Because it felt crummy.",
    "Why did the picture go to jail?": "Because it was framed.",
    "Why was the computer tired?": "It had too many tabs open.",
    "Why did the tomato turn red?": "Because it saw the salad dressing.",
    "Why don’t oysters donate to charity?": "Because they are shellfish.",
    "Why did the banana go to the doctor?": "Because it wasn’t peeling well.",

    "Why did the scarecrow get promoted?": "Because he was outstanding at his job.",
    "Why don’t cows have money?": "Because farmers milk them dry.",
    "Why did the stadium get hot after the game?": "All the fans left.",
    "Why did the math problem look so sad?": "Because it couldn’t find a solution.",
    "Why did the phone need glasses?": "Because it lost its contacts.",
    "Why was the belt arrested?": "For holding up the pants.",
    "Why did the computer go to therapy?": "Because it had too many issues.",
    "Why did the man put his money in the freezer?": "He wanted cold hard cash.",
    "Why don’t vampires like fast food?": "Because they can’t get a bite.",
    "Why did the calendar break up with the clock?": "It felt like time was running out.",

    "Why did the music teacher go to jail?": "For fingering the wrong notes.",
    "Why was the math lecture so long?": "The professor kept going off on a tangent.",
    "Why did the chicken join a band?": "Because it had the drumsticks.",
    "Why don’t ghosts lie?": "Because you can see right through them.",
    "Why did the pencil go to the principal’s office?": "Because it broke the rules.",
    "Why was the computer cold?": "It forgot to close its Windows.",
    "Why did the man bring a ladder to the bar?": "Because he heard the drinks were on the house.",
    "Why did the orange stop rolling downhill?": "Because it ran out of juice.",
    "Why don’t skeletons play music in church?": "Because they have no organs.",
    "Why did the cow win an award?": "Because it was outstanding in its field.",

    "Why did the man bring string to the office?": "To tie up loose ends.",
    "Why did the computer go broke?": "Because it lost its cache.",
    "Why did the math book look unhappy?": "It was full of problems.",
    "Why don’t programmers like dark mode jokes?": "They can’t see the point.",
    "Why did the printer get mad?": "Because it was out of paper.",
    "Why did the robot go on vacation?": "It needed to recharge.",
    "Why did the scarecrow retire?": "Because he was out standing too long.",
    "Why did the USB stick feel insecure?": "Because it was always getting rejected.",
    "Why did the server go to the gym?": "To work on its core.",
    "Why did the WiFi break up with the router?": "Too many connection issues."
}